### ISSUE TITLE
升级微信版本

### ISSUE THREAD

**Issue by Lucas-Wye** [top-bettercode/docker-wechat#42]
目前的版本是2.6，作者有没有在考虑升级版本？

**Comment by jicki** [comment]
可以自己测试一下升级~

**Comment by FreezeSoul** [comment]
docker exec -it wechat bash
mkdir /tmp/wechat
cd /tmp/wechat
wget https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
su wechat
env WINEPREFIX=/home/wechat/.deepinwine/Deepin-WeChat deepin-wine WeChatSetup.exe

**Comment by zineos** [comment]
@FreezeSoul 我试过了，显示系统不支持该版本微信，然后让下载系统可用版本

**Comment by FreezeSoul** [comment]
最新版的3.3.0 应该是不支持xp了，deepin-wine默认应该是xp，你可以从下面下载3.3.0之前的版本
https://weixin.qq.com/cgi-bin/readtemplate?t=weixin_faq_list

**Comment by Mrli2016** [comment]
> docker exec -it wechat bash mkdir /tmp/wechat cd /tmp/wechat wget https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe su wechat env WINEPREFIX=/home/wechat/.deepinwine/Deepin-WeChat deepin-wine WeChatSetup.exe

根据你说的我去试了下，最新可以更新到3.2.1版本
```
docker exec -it wechat bash
mkdir /tmp/wechat
cd /tmp/wechat
wget https://dldir1.qq.com/weixin/Windows/WeChat_for_XP_SP3_To_Vista.exe
su wechat
env WINEPREFIX=/home/wechat/.deepinwine/Deepin-WeChat deepin-wine WeChat_for_XP_SP3_To_Vista.exe
```
